repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=8192]
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: "(conda.recipe/meta.yaml|.travis.yml)"
      - id: end-of-file-fixer
        exclude: "(tests/data/.*|docs/_build/.*)"
      - id: trailing-whitespace
        exclude: "(tests/data/.*|docs/_build/.*)"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: "(tests/data/.*|docs/_build/.*)"
      - id: ruff-format
        exclude: "(tests/data/.*|docs/_build/.*)"
