sudo: false
# dist: trusty

language: python

python:
#  - 2.7
  - 3.5

sudo: false
env:
  global:
    - secure: "g6BVthPkjklTgzs/7Lu3OW9ruVdyQaamxBQra/Aw9HpLFSb2e4TFU9qbyYkRVxZqllKHnxm8Fq4d7PhUy+hGGNpN+9dgnf/IPmxS27b0+5ZlTuPbqv33kztQmfwwOhHQEWal6liROSQyZIW6a/QarFE6Loj0TeYXSmKiT2gNnzgAfJj1Tdj3R+gyqS5YgWVt9Tl31gjkEt7xEdfZKam0/j1lvD5ImzsH3X+mPiAGMkCrmEvyElsd2Ytylb5e4xp4wO+zJWgWO1oRdXqrSSgM2zgKw2A8ukkUqdI9c4alQbyzTdXeoj7mpWSBsAR++8tqK7qqh21zX3lRwOAy+DahDPmFgwVGjfa9NOOaDiLdRoFprpdqo5HOZOMttfDXu5velT+Oo6XMQDSeKhBV0ZPnNZHz8baJAtcrYcl/QiuiLb+YXGJZ0j7/lRTs/2y/8dpdG3SkyZzVnfr6PcP2UjbqQYypEBQEEx/AN1AqTAeqdKQP9zpyDRMpJSHRSSxJBAbdVKxuPrkTkb8MfBjY+qUmsrfAqnwl/ISvaq+wCNs5UqMOIybInf0sLTLUPnmiDcju/BsgfHZVuu/f04e5KCiUoRQW7AXfZl5yDoY1P5TkB4bK66UO6DRya24rSkkOOtY7Cer35JaXln0NVjNFPzyyrehzigsM18PC23dYS3foVBk="

# branches:
#   only:
#    - master
#
# services:
#
# matrix:
#  include:
#    - os: linux
   
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

after_success:
  - codecov

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda config --set always_yes true
  - conda update conda
  - conda create -n testenv pip nose python=$TRAVIS_PYTHON_VERSION numpy astropy scipy pandas cython
#  - conda install -n testenv -c scikit-xray xraylib lmfit=0.8.3 netcdf4 # install from scikit-xray channel 
  - source activate testenv
  - python setup.py install
#  - pip install coveralls
  - pip install codecov
  - pip install rednose
  - pip install coverage

script:
  - nosetests -v --rednose --cover-package=neutronbraggedge --with-coverage 
#  - set -e
#  - pip install doctr
#  - cd docs
#  - make html
#  - cd ..
#  - doctr deploy . --built-docs path/to/html

#   - python tests/getdata.py
#   - python tests/ivenus/signon.py


notifications:
  email:
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6b9d6dacd08d3e45e1b3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
